name: 测试

on: [pull_request, push]

jobs:
  golang:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Go 环境
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: 运行测试并生成覆盖率报告
        run: go test -v -race -coverprofile=coverage.txt ./...

      - name: 上传覆盖率报告
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: 构建项目
        run: make build
